version: "3"

services:

  server:
    image: node/server
    build: .
    ports:
      - "3000:3000"
    command: npm start
    environment:
      PORT: 3000
      DB_USERNAME: root
      DB_PASSWORD: crud_db
      DB_DATABASE: crud_db
      DB_HOSTNAME: mysql
    volumes:
      - .:/usr/server

  mysql:
    image: mysql:5.7
    container_name: crud_db
    environment:
      MYSQL_ROOT_PASSWORD: crud_db
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"