version: "3"

services:

  server:
    image: node/server
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/server

  zenvia_db:
    image: mysql:5.7
    container_name: crud_db
    environment:
      MYSQL_ROOT_PASSWORD: crud_db
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"